[theme]
# Base can be "light" or "dark"
base = "dark"

[server]
# Increases the maximum allowed file size to 500MB
maxUploadSize = 100 

# Increases the WebSocket message size limit to prevent mid-transfer crashes
maxMessageSize = 500
